# Generated by Django 5.1 on 2024-09-20 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15, verbose_name='カテゴリー名')),
                ('page_date', models.DateTimeField(verbose_name='日付')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
    ]
