# Generated by Django 5.1 on 2024-09-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='context',
            new_name='comment',
        ),
    ]
