# Generated by Django 5.1 on 2024-09-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_context_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(default='aiueo', max_length=30),
            preserve_default=False,
        ),
    ]
