# Generated by Django 5.1 on 2024-10-22 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='教育レベル', to='vocabulary.difficulty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_meaning', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('example_meaning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='vocabulary.partofspeech')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='vocabulary.words')),
            ],
        ),
    ]
